In [159]:
# importing the necessary libraries
import numpy as np
import pandas as pd
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split
from sklearn import linear_model
from sklearn.metrics import r2_score
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error
from sklearn.metrics import mean_squared_error
from sklearn.linear_model import Ridge
from sklearn.linear_model import Lasso

In [160]:
energy = pd.read_csv('C:\python\Hamoye\energydata_complete.csv')
energy

,date,Appliances,lights,T1,RH_1,T2,RH_2,T3,RH_3,T4,...,T9,RH_9,T_out,Press_mm_hg,RH_out,Windspeed,Visibility,Tdewpoint,rv1,rv2
0,2016-01-11 17:00:00,60,30,19.890000,47.596667,19.200000,44.790000,19.790000,44.730000,19.000000,...,17.033333,45.5300,6.60,733.5,92.000000,7.000000,63.000000,5.3,13.275433,13.275433
1,2016-01-11 17:10:00,60,30,19.890000,46.693333,19.200000,44.722500,19.790000,44.790000,19.000000,...,17.066667,45.5600,6.48,733.6,92.000000,6.666667,59.166667,5.2,18.606195,18.606195
2,2016-01-11 17:20:00,50,30,19.890000,46.300000,19.200000,44.626667,19.790000,44.933333,18.926667,...,17.000000,45.5000,6.37,733.7,92.000000,6.333333,55.333333,5.1,28.642668,28.642668
3,2016-01-11 17:30:00,50,40,19.890000,46.066667,19.200000,44.590000,19.790000,45.000000,18.890000,...,17.000000,45.4000,6.25,733.8,92.000000,6.000000,51.500000,5.0,45.410390,45.410390
4,2016-01-11 17:40:00,60,40,19.890000,46.333333,19.200000,44.530000,19.790000,45.000000,18.890000,...,17.000000,45.4000,6.13,733.9,92.000000,5.666667,47.666667,4.9,10.084097,10.084097
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19730,2016-05-27 17:20:00,100,0,25.566667,46.560000,25.890000,42.025714,27.200000,41.163333,24.700000,...,23.200000,46.7900,22.70,755.2,55.666667,3.333333,23.666667,13.3,43.096812,43.096812
19731,2016-05-27 17:30:00,90,0,25.500000,46.500000,25.754000,42.080000,27.133333,41.223333,24.700000,...,23.200000,46.7900,22.60,755.2,56.000000,3.500000,24.500000,13.3,49.282940,49.282940
19732,2016-05-27 17:40:00,270,10,25.500000,46.596667,25.628571,42.768571,27.050000,41.690000,24.700000,...,23.200000,46.7900,22.50,755.2,56.333333,3.666667,25.333333,13.3,29.199117,29.199117
19733,2016-05-27 17:50:00,420,10,25.500000,46.990000,25.414000,43.036000,26.890000,41.290000,24.700000,...,23.200000,46.8175,22.30,755.2,56.666667,3.833333,26.166667,13.2,6.322784,6.322784
19734,2016-05-27 18:00:00,430,10,25.500000,46.600000,25.264286,42.971429,26.823333,41.156667,24.700000,...,23.200000,46.8450,22.20,755.2,57.000000,4.000000,27.000000,13.2,34.118851,34.118851

In [161]:
energy.columns

Index(['date', 'Appliances', 'lights', 'T1', 'RH_1', 'T2', 'RH_2', 'T3',
       'RH_3', 'T4', 'RH_4', 'T5', 'RH_5', 'T6', 'RH_6', 'T7', 'RH_7', 'T8',
       'RH_8', 'T9', 'RH_9', 'T_out', 'Press_mm_hg', 'RH_out', 'Windspeed',
       'Visibility', 'Tdewpoint', 'rv1', 'rv2'],
      dtype='object')

These are the columns contained in the dataset

In [162]:
energy.dtypes

date            object
Appliances       int64
lights           int64
T1             float64
RH_1           float64
T2             float64
RH_2           float64
T3             float64
RH_3           float64
T4             float64
RH_4           float64
T5             float64
RH_5           float64
T6             float64
RH_6           float64
T7             float64
RH_7           float64
T8             float64
RH_8           float64
T9             float64
RH_9           float64
T_out          float64
Press_mm_hg    float64
RH_out         float64
Windspeed      float64
Visibility     float64
Tdewpoint      float64
rv1            float64
rv2            float64
dtype: object

This is a quiz on linear regression which requires numerical data for the model and every data in here are numerical except the 'date' columns. The column will be dropped soon.

In [163]:
energy1 = energy.drop(columns=['date', 'lights'])

<h4> Normalizing the dataset using MinMax scaler

In [164]:
# Normalizing
scalar = MinMaxScaler()
normalized_energy = pd.DataFrame(
    scalar.fit_transform(energy1), columns=energy1.columns)

# Splitting to feature and target variables
energy_x = normalized_energy.drop('Appliances', axis=1)
target_y = normalized_energy['Appliances']

<h4>Fitting a linear model on the relationship between T2 and T6

In [165]:
T2_T6 = normalized_energy[['T2', 'T6']]

# Why is this reshapep... maybe because it doesnot accept one dimensional
T2_T6x = T2_T6['T2'].values.reshape(-1, 1)
T2_T6y = T2_T6['T6'].values.reshape(-1, 1)

# splitting to train and test set
x_train, x_test, y_train, y_test = train_test_split(T2_T6x, T2_T6y,
                                                    test_size=0.30, random_state=42)

In [166]:
# The linear model
T2_T6_linear_model = linear_model.LinearRegression()
T2_T6_linear_model.fit(x_train, y_train)
T2_T6_linear_model_pred = T2_T6_linear_model.predict(x_test)
T2_T6_r2_score = r2_score(y_test, T2_T6_linear_model_pred)
r2 = round(T2_T6_r2_score, 2)
display('r2_score of...', r2)

'r2_score of...'

0.64

<h3>Training this model on the main dataset

In [167]:
# splitting to train and test sets
train_x, test_x, train_y, test_y = train_test_split(energy_x, target_y,
                                                    test_size=0.30, random_state=42)

In [168]:
linear_model = LinearRegression()
linear_model.fit(train_x, train_y)
pred_values = linear_model.predict(test_x)

In [169]:

mae = mean_absolute_error(test_y, pred_values)
print('The MAE is', (round(mae, 2)))

The MAE is 0.05

In [170]:
rss = np.sum(np.square(test_y - pred_values))
print('The RSS is', (round(rss, 2)))

The RSS is 45.35

In [171]:

rmse = np.sqrt(mean_squared_error(test_y, pred_values))
print('The RMSE is', (round(rmse, 3)))

The RMSE is 0.088

In [172]:
from sklearn.metrics import r2_score
r2 = r2_score(test_y, pred_values)
print('R square, also known as coefficient of determination is', (round(r2, 2)))

R square, also known as coefficient of determination is 0.15

In [173]:
# comparing the effect of the regularisation

def get_weight_energy(model, feat, col_name):
    '''This function returns the weight of every feature'''
    weights = pd.Series(model.coef_, feat.columns).sort_values()
    weights_energy = pd.DataFrame(weights).reset_index()
    weights_energy.columns = ['Features', col_name]
    weights_energy[col_name].round(3)
    return weights_energy


linear_model_weight = get_weight_energy(
    linear_model, train_x, 'Linear_Model_Weight')
linear_model_weight

       Features  Linear_Model_Weight
0           rv2        -2.858253e+10
1          RH_2        -4.566772e-01
2         T_out        -3.219790e-01
3            T2        -2.362059e-01
4            T9        -1.899774e-01
5          RH_8        -1.575836e-01
6        RH_out        -7.775338e-02
7          RH_7        -4.462442e-02
8          RH_9        -3.980654e-02
9            T5        -1.564247e-02
10           T1        -3.241639e-03
11  Press_mm_hg         6.831967e-03
12           T7         1.034189e-02
13   Visibility         1.230588e-02
14         RH_5         1.600661e-02
15         RH_4         2.636778e-02
16           T4         2.895025e-02
17    Windspeed         2.917674e-02
18         RH_6         3.802092e-02
19         RH_3         9.610582e-02
20           T8         1.020018e-01
21    Tdewpoint         1.178726e-01
22           T6         2.364438e-01
23           T3         2.905959e-01
24         RH_1         5.535172e-01
25          rv1         2.858253e+10

rv1 has the highest weight and rv2 has the lowest

<h4>Training a Ridge Regression model

In [174]:
ridge = Ridge(alpha=0.4)
ridge.fit(train_x, train_y)
ridge_prediction = ridge.predict(test_x)
rmse = np.sqrt(mean_squared_error(test_y, ridge_prediction))
print('The RMSE is', (round(rmse, 3)))

The RMSE is 0.088

The RMSE remains the same after fitting with the ridge regresion.

<h4>Training a Lasso Regression model

In [175]:
lasso = Lasso(alpha=0.001)
lasso.fit(train_x, train_y)
lasso_prediction = lasso.predict(test_x)
linear_model_weight = get_weight_energy(lasso, train_x, 'Lasso_Weight')
linear_model_weight.sort_values(by='Lasso_Weight')

       Features  Lasso_Weight
0        RH_out     -0.049557
1          RH_8     -0.000110
23          rv2     -0.000000
22         RH_6     -0.000000
21           T2      0.000000
20         RH_2     -0.000000
19           T3      0.000000
18         RH_3      0.000000
17           T4     -0.000000
16         RH_4      0.000000
15           T5     -0.000000
14         RH_5      0.000000
13           T6      0.000000
12           T7     -0.000000
11          rv1     -0.000000
10         RH_7     -0.000000
9            T8      0.000000
8            T9     -0.000000
7          RH_9     -0.000000
6         T_out      0.000000
5   Press_mm_hg     -0.000000
4    Visibility      0.000000
3     Tdewpoint      0.000000
2            T1      0.000000
24    Windspeed      0.002912
25         RH_1      0.017880

RH_out, RH_8, Windspeed and RH_1 has a non-zero feature, so there are just 4 of them.

In [176]:

rmse = np.sqrt(mean_squared_error(test_y, lasso_prediction))
print('The RMSE is', (round(rmse, 3)))

The RMSE is 0.094